
version: '3.9'

services:

    jupyter:
        environment:
            JUPYTER_TOKEN: "docker"
        build: .
        image: film_frame_interpolation
        ports:
            - 8888:8888
        volumes:
            - ./project_volume:/content/project_volume
        command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root
        deploy:
            resources:
                reservations:
                    devices:
                    - capabilities: [gpu]